import Head from 'next/head'
import Image from 'next/image'
import { Col, Row } from 'react-bootstrap'
import About from '../components/About'
import Banner from '../components/Banner'
import Charge from '../components/Charge'
import Contact from '../components/Contact'
import Footer from '../components/Footer'
import Projects from '../components/Projects'
import Skills from '../components/Skills'

export default function Home() {
  return (
    <div className="bg-custom-primary" style={{minHeight: '100vh',overflow: 'hidden'}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Banner />
        <div className="container-md">
          <Projects />
          <About />
          <Skills />
          <Charge />
          <Contact />
          <Footer />
        </div>
      </main>

    </div>
  )
}
